flags = [
{ code: "🇦🇨", item: "Ascension Island"},
{ code: "🇦🇩", item: "Andorra"},
{ code: "🇦🇪", item: "United Arab Emirates"},
{ code: "🇦🇫", item: "Afghanistan"},
{ code: "🇦🇬", item: "Antigua & Barbuda"},
{ code: "🇦🇮", item: "Anguilla"},
{ code: "🇦🇱", item: "Albania"},
{ code: "🇦🇲", item: "Armenia"},
{ code: "🇦🇴", item: "Angola"},
{ code: "🇦🇶", item: "Antarctica"},
{ code: "🇦🇷", item: "Argentina"},
{ code: "🇦🇸", item: "American Samoa"},
{ code: "🇦🇹", item: "Austria"},
{ code: "🇦🇺", item: "Australia"},
{ code: "🇦🇼", item: "Aruba"},
{ code: "🇦🇽", item: "Åland Islands"},
{ code: "🇦🇿", item: "Azerbaijan"},
{ code: "🇧🇦", item: "Bosnia & Herzegovina"},
{ code: "🇧🇧", item: "Barbados"},
{ code: "🇧🇩", item: "Bangladesh"},
{ code: "🇧🇪", item: "Belgium"},
{ code: "🇧🇫", item: "Burkina Faso"},
{ code: "🇧🇬", item: "Bulgaria"},
{ code: "🇧🇭", item: "Bahrain"},
{ code: "🇧🇮", item: "Burundi"},
{ code: "🇧🇯", item: "Benin"},
{ code: "🇧🇱", item: "St. Barthélemy"},
{ code: "🇧🇲", item: "Bermuda"},
{ code: "🇧🇳", item: "Brunei"},
{ code: "🇧🇴", item: "Bolivia"},
{ code: "🇧🇶", item: "Caribbean Netherlands"},
{ code: "🇧🇷", item: "Brazil"},
{ code: "🇧🇸", item: "Bahamas"},
{ code: "🇧🇹", item: "Bhutan"},
{ code: "🇧🇻", item: "Bouvet Island"},
{ code: "🇧🇼", item: "Botswana"},
{ code: "🇧🇾", item: "Belarus"},
{ code: "🇧🇿", item: "Belize"},
{ code: "🇨🇦", item: "Canada"},
{ code: "🇨🇨", item: "Cocos (Keeling) Islands"},
{ code: "🇨🇩", item: "Congo - Kinshasa"},
{ code: "🇨🇫", item: "Central African Republic"},
{ code: "🇨🇬", item: "Congo - Brazzaville"},
{ code: "🇨🇭", item: "Switzerland"},
{ code: "🇨🇮", item: "Côte d’Ivoire"},
{ code: "🇨🇰", item: "Cook Islands"},
{ code: "🇨🇱", item: "Chile"},
{ code: "🇨🇲", item: "Cameroon"},
{ code: "🇨🇳", item: "China"},
{ code: "🇨🇴", item: "Colombia"},
{ code: "🇨🇵", item: "Clipperton Island"},
{ code: "🇨🇷", item: "Costa Rica"},
{ code: "🇨🇺", item: "Cuba"},
{ code: "🇨🇻", item: "Cape Verde"},
{ code: "🇨🇼", item: "Curaçao"},
{ code: "🇨🇽", item: "Christmas Island"},
{ code: "🇨🇾", item: "Cyprus"},
{ code: "🇨🇿", item: "Czechia"},
{ code: "🇩🇪", item: "Germany"},
{ code: "🇩🇬", item: "Diego Garcia"},
{ code: "🇩🇯", item: "Djibouti"},
{ code: "🇩🇰", item: "Denmark"},
{ code: "🇩🇲", item: "Dominica"},
{ code: "🇩🇴", item: "Dominican Republic"},
{ code: "🇩🇿", item: "Algeria"},
{ code: "🇪🇦", item: "Ceuta & Melilla"},
{ code: "🇪🇨", item: "Ecuador"},
{ code: "🇪🇪", item: "Estonia"},
{ code: "🇪🇬", item: "Egypt"},
{ code: "🇪🇭", item: "Western Sahara"},
{ code: "🇪🇷", item: "Eritrea"},
{ code: "🇪🇸", item: "Spain"},
{ code: "🇪🇹", item: "Ethiopia"},
{ code: "🇪🇺", item: "European Union"},
{ code: "🇫🇮", item: "Finland"},
{ code: "🇫🇯", item: "Fiji"},
{ code: "🇫🇰", item: "Falkland Islands"},
{ code: "🇫🇲", item: "Micronesia"},
{ code: "🇫🇴", item: "Faroe Islands"},
{ code: "🇫🇷", item: "France"},
{ code: "🇬🇦", item: "Gabon"},
{ code: "🇬🇧", item: "United Kingdom"},
{ code: "🇬🇩", item: "Grenada"},
{ code: "🇬🇪", item: "Georgia"},
{ code: "🇬🇫", item: "French Guiana"},
{ code: "🇬🇬", item: "Guernsey"},
{ code: "🇬🇭", item: "Ghana"},
{ code: "🇬🇮", item: "Gibraltar"},
{ code: "🇬🇱", item: "Greenland"},
{ code: "🇬🇲", item: "Gambia"},
{ code: "🇬🇳", item: "Guinea"},
{ code: "🇬🇵", item: "Guadeloupe"},
{ code: "🇬🇶", item: "Equatorial Guinea"},
{ code: "🇬🇷", item: "Greece"},
{ code: "🇬🇸", item: "South Georgia & South Sandwich Islands"},
{ code: "🇬🇹", item: "Guatemala"},
{ code: "🇬🇺", item: "Guam"},
{ code: "🇬🇼", item: "Guinea-Bissau"},
{ code: "🇬🇾", item: "Guyana"},
{ code: "🇭🇰", item: "Hong Kong SAR China"},
{ code: "🇭🇲", item: "Heard & McDonald Islands"},
{ code: "🇭🇳", item: "Honduras"},
{ code: "🇭🇷", item: "Croatia"},
{ code: "🇭🇹", item: "Haiti"},
{ code: "🇭🇺", item: "Hungary"},
{ code: "🇮🇨", item: "Canary Islands"},
{ code: "🇮🇩", item: "Indonesia"},
{ code: "🇮🇪", item: "Ireland"},
{ code: "🇮🇱", item: "Israel"},
{ code: "🇮🇲", item: "Isle of Man"},
{ code: "🇮🇳", item: "India"},
{ code: "🇮🇴", item: "British Indian Ocean Territory"},
{ code: "🇮🇶", item: "Iraq"},
{ code: "🇮🇷", item: "Iran"},
{ code: "🇮🇸", item: "Iceland"},
{ code: "🇮🇹", item: "Italy"},
{ code: "🇯🇪", item: "Jersey"},
{ code: "🇯🇲", item: "Jamaica"},
{ code: "🇯🇴", item: "Jordan"},
{ code: "🇯🇵", item: "Japan"},
{ code: "🇰🇪", item: "Kenya"},
{ code: "🇰🇬", item: "Kyrgyzstan"},
{ code: "🇰🇭", item: "Cambodia"},
{ code: "🇰🇮", item: "Kiribati"},
{ code: "🇰🇲", item: "Comoros"},
{ code: "🇰🇳", item: "St. Kitts & Nevis"},
{ code: "🇰🇵", item: "North Korea"},
{ code: "🇰🇷", item: "South Korea"},
{ code: "🇰🇼", item: "Kuwait"},
{ code: "🇰🇾", item: "Cayman Islands"},
{ code: "🇰🇿", item: "Kazakhstan"},
{ code: "🇱🇦", item: "Laos"},
{ code: "🇱🇧", item: "Lebanon"},
{ code: "🇱🇨", item: "St. Lucia"},
{ code: "🇱🇮", item: "Liechtenstein"},
{ code: "🇱🇰", item: "Sri Lanka"},
{ code: "🇱🇷", item: "Liberia"},
{ code: "🇱🇸", item: "Lesotho"},
{ code: "🇱🇹", item: "Lithuania"},
{ code: "🇱🇺", item: "Luxembourg"},
{ code: "🇱🇻", item: "Latvia"},
{ code: "🇱🇾", item: "Libya"},
{ code: "🇲🇦", item: "Morocco"},
{ code: "🇲🇨", item: "Monaco"},
{ code: "🇲🇩", item: "Moldova"},
{ code: "🇲🇪", item: "Montenegro"},
{ code: "🇲🇫", item: "St. Martin"},
{ code: "🇲🇬", item: "Madagascar"},
{ code: "🇲🇭", item: "Marshall Islands"},
{ code: "🇲🇰", item: "North Macedonia"},
{ code: "🇲🇱", item: "Mali"},
{ code: "🇲🇲", item: "Myanmar (Burma)"},
{ code: "🇲🇳", item: "Mongolia"},
{ code: "🇲🇴", item: "Macao Sar China"},
{ code: "🇲🇵", item: "Northern Mariana Islands"},
{ code: "🇲🇶", item: "Martinique"},
{ code: "🇲🇷", item: "Mauritania"},
{ code: "🇲🇸", item: "Montserrat"},
{ code: "🇲🇹", item: "Malta"},
{ code: "🇲🇺", item: "Mauritius"},
{ code: "🇲🇻", item: "Maldives"},
{ code: "🇲🇼", item: "Malawi"},
{ code: "🇲🇽", item: "Mexico"},
{ code: "🇲🇾", item: "Malaysia"},
{ code: "🇲🇿", item: "Mozambique"},
{ code: "🇳🇦", item: "Namibia"},
{ code: "🇳🇨", item: "New Caledonia"},
{ code: "🇳🇪", item: "Niger"},
{ code: "🇳🇫", item: "Norfolk Island"},
{ code: "🇳🇬", item: "Nigeria"},
{ code: "🇳🇮", item: "Nicaragua"},
{ code: "🇳🇱", item: "Netherlands"},
{ code: "🇳🇴", item: "Norway"},
{ code: "🇳🇵", item: "Nepal"},
{ code: "🇳🇷", item: "Nauru"},
{ code: "🇳🇺", item: "Niue"},
{ code: "🇳🇿", item: "New Zealand"},
{ code: "🇴🇲", item: "Oman"},
{ code: "🇵🇦", item: "Panama"},
{ code: "🇵🇪", item: "Peru"},
{ code: "🇵🇫", item: "French Polynesia"},
{ code: "🇵🇬", item: "Papua New Guinea"},
{ code: "🇵🇭", item: "Philippines"},
{ code: "🇵🇰", item: "Pakistan"},
{ code: "🇵🇱", item: "Poland"},
{ code: "🇵🇲", item: "St. Pierre & Miquelon"},
{ code: "🇵🇳", item: "Pitcairn Islands"},
{ code: "🇵🇷", item: "Puerto Rico"},
{ code: "🇵🇸", item: "Palestinian Territories"},
{ code: "🇵🇹", item: "Portugal"},
{ code: "🇵🇼", item: "Palau"},
{ code: "🇵🇾", item: "Paraguay"},
{ code: "🇶🇦", item: "Qatar"},
{ code: "🇷🇪", item: "Réunion"},
{ code: "🇷🇴", item: "Romania"},
{ code: "🇷🇸", item: "Serbia"},
{ code: "🇷🇺", item: "Russia"},
{ code: "🇷🇼", item: "Rwanda"},
{ code: "🇸🇦", item: "Saudi Arabia"},
{ code: "🇸🇧", item: "Solomon Islands"},
{ code: "🇸🇨", item: "Seychelles"},
{ code: "🇸🇩", item: "Sudan"},
{ code: "🇸🇪", item: "Sweden"},
{ code: "🇸🇬", item: "Singapore"},
{ code: "🇸🇭", item: "St. Helena"},
{ code: "🇸🇮", item: "Slovenia"},
{ code: "🇸🇯", item: "Svalbard & Jan Mayen"},
{ code: "🇸🇰", item: "Slovakia"},
{ code: "🇸🇱", item: "Sierra Leone"},
{ code: "🇸🇲", item: "San Marino"},
{ code: "🇸🇳", item: "Senegal"},
{ code: "🇸🇴", item: "Somalia"},
{ code: "🇸🇷", item: "Suriname"},
{ code: "🇸🇸", item: "South Sudan"},
{ code: "🇸🇹", item: "São Tomé & Príncipe"},
{ code: "🇸🇻", item: "El Salvador"},
{ code: "🇸🇽", item: "Sint Maarten"},
{ code: "🇸🇾", item: "Syria"},
{ code: "🇸🇿", item: "Eswatini"},
{ code: "🇹🇦", item: "Tristan Da Cunha"},
{ code: "🇹🇨", item: "Turks & Caicos Islands"},
{ code: "🇹🇩", item: "Chad"},
{ code: "🇹🇫", item: "French Southern Territories"},
{ code: "🇹🇬", item: "Togo"},
{ code: "🇹🇭", item: "Thailand"},
{ code: "🇹🇯", item: "Tajikistan"},
{ code: "🇹🇰", item: "Tokelau"},
{ code: "🇹🇱", item: "Timor-Leste"},
{ code: "🇹🇲", item: "Turkmenistan"},
{ code: "🇹🇳", item: "Tunisia"},
{ code: "🇹🇴", item: "Tonga"},
{ code: "🇹🇷", item: "Turkey"},
{ code: "🇹🇹", item: "Trinidad & Tobago"},
{ code: "🇹🇻", item: "Tuvalu"},
{ code: "🇹🇼", item: "Taiwan"},
{ code: "🇹🇿", item: "Tanzania"},
{ code: "🇺🇦", item: "Ukraine"},
{ code: "🇺🇬", item: "Uganda"},
{ code: "🇺🇲", item: "U.S. Outlying Islands"},
{ code: "🇺🇳", item: "United Nations"},
{ code: "🇺🇸", item: "United States"},
{ code: "🇺🇾", item: "Uruguay"},
{ code: "🇺🇿", item: "Uzbekistan"},
{ code: "🇻🇦", item: "Vatican City"},
{ code: "🇻🇨", item: "St. Vincent & Grenadines"},
{ code: "🇻🇪", item: "Venezuela"},
{ code: "🇻🇬", item: "British Virgin Islands"},
{ code: "🇻🇮", item: "U.S. Virgin Islands"},
{ code: "🇻🇳", item: "Vietnam"},
{ code: "🇻🇺", item: "Vanuatu"},
{ code: "🇼🇫", item: "Wallis & Futuna"},
{ code: "🇼🇸", item: "Samoa"},
{ code: "🇽🇰", item: "Kosovo"},
{ code: "🇾🇪", item: "Yemen"},
{ code: "🇾🇹", item: "Mayotte"},
{ code: "🇿🇦", item: "South Africa"},
{ code: "🇿🇲", item: "Zambia"},
{ code: "🇿🇼", item: "Zimbabwe"},
{ code: "🇬🇧", item: "England"},
{ code: "&#127988;&#917607;&#917602;&#917619;&#917603;&#917620;&#917631;", item: "Scotland"},
{ code: "&#127988;&#917607;&#917602;&#917623;&#917612;&#917619;&#917631;", item: "Wales"}
 ];
